### PR TITLE
Update users.php

### PR DESCRIPTION
**Pull request by oe1kbc**
missing ./ to show correct logo

### CODE REVIEW

**Comment by kc1awv** [comment]
This seems to be a browser-based issue which I can not replicate locally. Can you provide a screenshot or a deeper explanation of the issue being fixed here?

**Comment by ghost** [comment]
Maybe oe1kbc is hosting the dashboard under a directory?

**Comment by oe1kbc** [comment]
yes right, we run more services so use /var/www/http/m17 and we use host-header recognition http://m17-aut.xreflector.net
so it is usefull to write ./images instead og /images
73
Kurt

**Comment by kc1awv** [comment]
Thank you for helping me understand. I realize now that not everyone will be running mrefd exclusively on a webserver, so relative links are best.

**Pull request merged**
